# Generated by Django 2.2.5 on 2019-10-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(default='Active', max_length=60),
            preserve_default=False,
        ),
    ]
