# Generated by Django 2.2.5 on 2019-11-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='creator',
            field=models.IntegerField(),
        ),
    ]
