# Generated by Django 2.2.5 on 2019-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20191103_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='creator',
            field=models.CharField(max_length=256),
        ),
    ]
