# Generated by Django 2.2.5 on 2019-09-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190925_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='creation_date',
        ),
    ]
