# Generated by Django 2.2.5 on 2019-10-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
